import type { CSSProperties } from "react";

export const opsStyles: Record<string, CSSProperties> = {
  page: {
    fontFamily: "system-ui, sans-serif",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    background: "#f8fafc",
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 10,
    flexShrink: 0,
    background: "#fff",
    borderBottom: "1px solid #e2e8f0",
    padding: "16px 24px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
  },
  headerInner: {
    maxWidth: 1024,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 600,
    letterSpacing: "-0.02em",
    color: "#1e293b",
    margin: 0,
  },
  nav: {
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  navLink: {
    fontSize: 13,
    padding: "6px 12px",
    color: "#1976d2",
    textDecoration: "none",
    fontWeight: 500,
    borderRadius: 6,
  },
  main: {
    flex: 1,
    overflow: "auto",
    padding: "24px",
  },
  mainInner: {
    maxWidth: 1024,
    margin: "0 auto",
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: 600,
    letterSpacing: "-0.02em",
    color: "#1e293b",
    margin: 0,
  },
  pageSubtitle: {
    fontSize: 13,
    color: "#64748b",
    marginTop: 4,
    marginBottom: 0,
  },
  section: {
    background: "#fff",
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
    overflow: "hidden",
    marginBottom: 24,
  },
  sectionHeader: {
    padding: "12px 24px",
    borderBottom: "1px solid #e2e8f0",
    background: "#fafafa",
    fontSize: 13,
    fontWeight: 600,
    color: "#334155",
  },
  sectionBody: {
    padding: 24,
  },
  label: {
    fontSize: 11,
    fontWeight: 500,
    color: "#64748b",
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    marginBottom: 6,
    display: "block",
  },
  input: {
    width: "100%",
    padding: "8px 12px",
    fontSize: 13,
    border: "1px solid #cbd5e1",
    borderRadius: 6,
    backgroundColor: "#fff",
    color: "#334155",
  },
  select: {
    padding: "8px 12px",
    fontSize: 13,
    border: "1px solid #cbd5e1",
    borderRadius: 6,
    backgroundColor: "#fff",
    color: "#334155",
  },
  textarea: {
    width: "100%",
    padding: 12,
    fontSize: 13,
    fontFamily: "monospace",
    border: "1px solid #cbd5e1",
    borderRadius: 6,
    backgroundColor: "#fff",
    color: "#334155",
    resize: "vertical",
    minHeight: 80,
  },
  btn: {
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 6,
    border: "none",
    cursor: "pointer",
  },
  btnPrimary: {
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 6,
    border: "none",
    cursor: "pointer",
    background: "#1976d2",
    color: "#fff",
  },
  btnSecondary: {
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 6,
    border: "1px solid #cbd5e1",
    cursor: "pointer",
    background: "#fff",
    color: "#475569",
  },
  btnSuccess: {
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 6,
    border: "none",
    cursor: "pointer",
    background: "#2e7d32",
    color: "#fff",
  },
  btnViolet: {
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 6,
    border: "none",
    cursor: "pointer",
    background: "#7b1fa2",
    color: "#fff",
  },
  error: {
    padding: 16,
    background: "#ffebee",
    border: "1px solid #ffcdd2",
    borderRadius: 6,
    color: "#c62828",
    fontSize: 13,
    fontWeight: 500,
    marginBottom: 24,
  },
  card: {
    background: "#fff",
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    padding: 20,
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
    marginBottom: 24,
  },
  table: {
    width: "100%",
    fontSize: 13,
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    padding: 12,
    fontWeight: 500,
    color: "#475569",
    background: "#fafafa",
    borderBottom: "1px solid #e2e8f0",
  },
  td: {
    padding: 12,
    color: "#334155",
    borderBottom: "1px solid #e2e8f0",
  },
  trHover: {
    // applied via onMouseEnter/Leave or wrapper
  },
  link: {
    color: "#1976d2",
    textDecoration: "none",
    fontWeight: 500,
  },
  jsonBlock: {
    overflow: "auto",
    borderRadius: 6,
    background: "#fafafa",
    border: "1px solid #e2e8f0",
    padding: 16,
    fontSize: 12,
    fontFamily: "monospace",
    color: "#334155",
    maxHeight: 384,
  },
  detailsSummary: {
    padding: "12px 24px",
    background: "#fafafa",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    color: "#475569",
    borderBottom: "1px solid #e2e8f0",
    listStyle: "none",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  detailsContent: {
    padding: 24,
  },
  tabBar: {
    display: "flex",
    borderBottom: "1px solid #e2e8f0",
  },
  tabButton: {
    padding: "10px 16px",
    fontSize: 13,
    fontWeight: 500,
    border: "none",
    borderBottom: "2px solid transparent",
    marginBottom: -1,
    cursor: "pointer",
    background: "#fafafa",
    color: "#64748b",
  },
  tabButtonActive: {
    padding: "10px 16px",
    fontSize: 13,
    fontWeight: 500,
    border: "none",
    borderBottom: "2px solid #1976d2",
    marginBottom: -1,
    cursor: "pointer",
    background: "#fff",
    color: "#1976d2",
  },
  gridRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
    gap: 16,
  },
  flexRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 16,
  },
  flexGap: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
  },
  spaceY: { display: "flex", flexDirection: "column", gap: 24 },
  muted: { fontSize: 13, color: "#64748b" },
};
